development:
  adapter: mysql2
  encoding: utf8
  database: talky_dev
  pool: 5
  username: pekoe
  password: Uei9wEXbKRCa
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: talky_test
  pool: 5
  username: simon
  password: 6O7MbIRT5HxJ
  socket: /tmp/mysql.sock

production:
 adapter: mysql2
 encoding: utf8
 database: talky_test
 pool: 5
 username: simon
 password: 6O7MbIRT5HxJ
 socket: /tmp/mysql.sock

