development:
  adapter: mysql2
  encoding: utf8
  database: talky_dev
  pool: 5
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: talky_test
  pool: 5
  socket: /tmp/mysql.sock


production:
  adapter: sqlite3
  encoding: utf8
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
